my-kanban/UserInterface/Models/ErrorViewModel.cs
namespace UserInterface.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

my-kanban/UserInterface/Controllers/BoardsController.cs
using Domain.Dtos;
using Microsoft.AspNetCore.Mvc;
using Service.Interfaces;
using System.Diagnostics;
using UserInterface.Models;

namespace UserInterface.Controllers
{
    public class BoardsController : Controller
    {
        private readonly ILogger<BoardsController> _logger;
        private readonly IBoardService _boardService;

        public BoardsController(ILogger<BoardsController> logger, IBoardService boardService)
        {
            _logger = logger;
            _boardService = boardService;
        }

        public IActionResult Index()
        {
            ViewBag.Boards = _boardService.GetAllBoards();
            return View();
        }

        public IActionResult NewBoard(string boardName, string boardDescription)
        {
            _boardService.CreateBoard(new BoardDto()
            {
                Name = boardName,
                Description = boardDescription
            });
            return RedirectToAction("Index");
        }

        public IActionResult Delete(string boardId)
        {
            _boardService.DeleteBoard(Convert.ToInt32(boardId));
            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

my-kanban/UserInterface/Controllers/TasksController.cs
using Domain.Dtos;
using Domain.Enums;
using Microsoft.AspNetCore.Mvc;
using Service.Interfaces;

namespace UserInterface.Controllers
{
    public class TasksController : Controller
    {
        private readonly IBoardService _boardService;
        private readonly ITaskService _taskService;

        public TasksController(IBoardService boardService, ITaskService taskService)
        {
            _boardService = boardService;
            _taskService = taskService;
        }

        public IActionResult Board(string boardId)
        {
            var id = Convert.ToInt32(boardId);
            ViewBag.BoardDetails = _boardService.GetBoardWithChildrenTasks(id);
            return View();
        }

        public IActionResult NewTask(string boardId, string taskName, string taskDescription)
        {
            _boardService.AddTask(
                Convert.ToInt32(boardId),
                new TaskDto()
                {
                    Name = taskName,
                    Description = taskDescription
                }
                );
            return RedirectToAction("Board", "Tasks", new { boardId });
        }

        public IActionResult SetToDoing(string taskId)
        {
            return AlterTaskState(taskId, TaskState.Doing);
        }
        public IActionResult SetToTodo(string taskId)
        {
            return AlterTaskState(taskId, TaskState.Todo);
        }
        public IActionResult SetToConcluded(string taskId)
        {
            return AlterTaskState(taskId, TaskState.Concluded);
        }
        public IActionResult SetToCanceled(string taskId)
        {
            return AlterTaskState(taskId, TaskState.Canceled);
        }
        private IActionResult AlterTaskState(string taskId, TaskState taskState) 
        {
            var boardId = _taskService.ChangeTaskState(Convert.ToInt32(taskId), taskState);
            return RedirectToAction("Board", "Tasks", new { boardId = boardId });
        }
    }
}

my-kanban/UserInterface/Views/Boards/Index.cshtml
@using Domain.Entities;
@{
    ViewData["Title"] = "Board Page";
    List<BoardEntity> boards = ViewBag.Boards;
}

<!-- Modal -->
<section id="boardModal" class="modal fade" tabindex="-1" aria-labelledby="boardModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <form class="modal-content" asp-controller="Boards" asp-action="NewBoard">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="boardModalLabel">Create New Board</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <label for="boardName" class="form-label">Board Name</label>
                    <input type="text" class="form-control" id="boardName" name="boardName" aria-describedby="boardNameHelp">
                    <div id="boardNameHelp" class="form-text">Define here the name that is related to the context of the board.</div>
                </div>
                <div class="mb-3">
                    <label for="boardDescription" class="form-label">Board Description</label>
                    <input type="text" class="form-control" id="boardDescription" name="boardDescription" aria-describedby="boardDescriptionHelp">
                    <div id="boardDescriptionHelp" class="form-text">Give it a short description that will help you remember why you created.</div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
        </form>
    </div>
</section>

<section id="board" class="p-3 row">
    <div class="col-10">
        <h2 class="display-6">My Boards</h2>
        <p class="text-muted">Manage your boards, create task contexts and keep up with all your routines.</p>
    </div>
    <div class="col-2 d-flex flex-column justify-content-center">
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#boardModal">
            New Board
        </button>
    </div>
    <hr />
</section>


<section class="container my-3 mx-3">
    <div class="row gx-3 gy-3">
        @foreach (var board in boards)
        {
            <div class="col-4">
                <div class="card" style="width: 25rem; height: 100%;">
                    <div class="card-header">
                        <h5 class="card-title"><strong>@board.Name</strong></h5>
                    </div>
                    <div class="card-body">
                        <small class="lead">@board.Description</small><br />
                        <small class="text-body-secondary text-muted">Last Update: @board.UpdatedAt.ToLongDateString()</small>
                    </div>
                    <div class="card-footer text-body-secondary">
                        <span class="card-body d-flex flex-row flex-nowrap justify-content-between">
                            <a asp-area="" asp-controller="Tasks" asp-action="Board" asp-route-boardId="@board.Id" class="btn btn-primary">View Tasks</a>
                            <div class="dropdown">
                                <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Configure
                                </a>

                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="#">Action</a></li>
                                    <li><a class="dropdown-item" href="#">Another action</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Boards" asp-action="Delete" asp-route-boardId="@board.Id">Delete Board</a></li>
                                </ul>
                            </div>
                        </span>
                    </div>
                </div>
            </div>
        }
    </div>
</section>

my-kanban/UserInterface/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UserInterface</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UserInterface.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Boards" asp-action="Index">My Kanban</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Boards" asp-action="Index">Boards</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Boards" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - UserInterface - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

my-kanban/UserInterface/Views/Tasks/Board.cshtml
@using Domain.Entities;
@using Domain.Enums;
@{
    ViewData["Title"] = "TaskBoard Page";
    BoardEntity boardDetails = ViewBag.BoardDetails;

    Dictionary<string, List<TaskEntity>> columns = new()
    {
        {"To-Do", boardDetails.Tasks.Where(t => t.Status == TaskState.Todo).ToList() },
        {"Doing", boardDetails.Tasks.Where(t => t.Status == TaskState.Doing).ToList() },
        {"Done", boardDetails.Tasks.Where(t => t.Status == TaskState.Canceled || t.Status == TaskState.Concluded).ToList() },
    };
}
<section id="board-details" class="p-3 row">
    <div class="col-10">
        <h2 class="display-6">@boardDetails.Name</h2>
        <p class="text-muted">@boardDetails.Description</p>
    </div>
    <div class="col-2 d-flex flex-column justify-content-center">
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#taskModal">
            New Task
        </button>
    </div>
    <hr />
</section>

<!-- Modal -->
<section id="taskModal" class="modal fade" tabindex="-1" aria-labelledby="taskModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <form class="modal-content" asp-controller="Tasks" asp-action="NewTask" asp-route-boardId="@boardDetails.Id">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="taskModalLabel">Create New Task</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <label for="taskName" class="form-label">Task Name</label>
                    <input type="text" class="form-control" id="taskName" name="taskName" aria-describedby="taskNameHelp">
                    <div id="taskNameHelp" class="form-text">Define here the name that is related to the context of the task.</div>
                </div>
                <div class="mb-3">
                    <label for="taskDescription" class="form-label">Task Description</label>
                    <input type="text" class="form-control" id="taskDescription" name="taskDescription" aria-describedby="taskDescriptionHelp">
                    <div id="taskDescriptionHelp" class="form-text">Give it a short description that will help you remember why you created.</div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
        </form>
    </div>
</section>

<section id="tasks" class="mx-4 mt-4">
    <div class="row">
        @foreach (KeyValuePair<string, List<TaskEntity>> column in columns)
        {
            <section id="@column.Key" class="col-4">
                <h3>@column.Key</h3>
                <div class="d-flex flex-column align-center">
                    @foreach (TaskEntity task in column.Value)
                    {
                        @if (task.Status == TaskState.Todo)
                        {
                            <div class="card text-light bg-primary mb-3" style="max-width: 18rem;">
                                <div class="card-header">@task.UpdatedAt</div>
                                <div class="card-body">
                                    <h5 class="card-title">@task.Name</h5>
                                    <p class="card-text">@task.Description</p>
                                </div>
                                <div class="card-footer text-center">
                                    <a asp-area="" asp-controller="Tasks" asp-action="SetToDoing" asp-route-taskId="@task.Id" class="btn btn-outline-light">Move Forward</a>
                                </div>
                            </div>
                        }
                        @if (task.Status == TaskState.Doing)
                        {
                            <div class="card bg-warning mb-3" style="max-width: 18rem;">
                                <div class="card-header">@task.UpdatedAt</div>
                                <div class="card-body">
                                    <h5 class="card-title">@task.Name</h5>
                                    <p class="card-text">@task.Description</p>
                                </div>
                                <div class="card-footer text-center">
                                    <section class="dropdown">
                                        <button class="btn btn-outline-light dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            Move Task
                                        </button>
                                        <ul class="dropdown-menu">
                                            <li><a asp-area="" asp-controller="Tasks" asp-action="SetToTodo" asp-route-taskId="@task.Id" class="dropdown-item">To Do</a></li>
                                            <li><a asp-area="" asp-controller="Tasks" asp-action="SetToConcluded" asp-route-taskId="@task.Id" class="dropdown-item">Concluded</a></li>
                                            <li><a asp-area="" asp-controller="Tasks" asp-action="SetToCanceled" asp-route-taskId="@task.Id" class="dropdown-item">Canceled</a></li>
                                        </ul>
                                    </section>
                                </div>
                            </div>

                        }
                        @if (task.Status == TaskState.Concluded || task.Status == TaskState.Canceled)
                        {
                            @if (task.Status == TaskState.Concluded)
                            {
                                <div class="card text-light bg-success mb-3" style="max-width: 18rem;">
                                    <div class="card-header">@task.UpdatedAt</div>
                                    <div class="card-body">
                                        <h5 class="card-title">@task.Name</h5>
                                        <p class="card-text">@task.Description</p>
                                    </div>
                                    <div class="card-footer text-center">
                                        <a asp-area="" asp-controller="Tasks" asp-action="SetToDoing" asp-route-taskId="@task.Id" class="btn btn-outline-light">Move Back</a>
                                    </div>
                                </div>
                            }
                            else
                            {
                                <div class="card text-light bg-danger mb-3" style="max-width: 18rem;">
                                    <div class="card-header">@task.UpdatedAt</div>
                                    <div class="card-body">
                                        <h5 class="card-title">@task.Name</h5>
                                        <p class="card-text">@task.Description</p>
                                    </div>
                                    <div class="card-footer text-center">
                                        <a asp-area="" asp-controller="Tasks" asp-action="SetToDoing" asp-route-taskId="@task.Id" class="btn btn-outline-light">Move Back</a>
                                    </div>
                                </div>
                            }
                        }
                    }
                </div>
            </section>
        }
    </div>
</section>